# Generated by Django 4.2.25 on 2025-10-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Symbol code e.g. BTCUSDT', max_length=40, unique=True)),
                ('ccxt_symbol', models.CharField(blank=True, help_text='Trading pair format used by ccxt (e.g. BTC/USDT)', max_length=40)),
                ('base_asset', models.CharField(max_length=20)),
                ('quote_asset', models.CharField(max_length=20)),
                ('exchange', models.CharField(default='binance', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=28)),
                ('source', models.CharField(default='ccxt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='datafeeds.symbol')),
            ],
            options={
                'ordering': ('symbol', 'timeframe', 'timestamp'),
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
