# Generated by Django 4.2.25 on 2025-10-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divergence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], max_length=5)),
                ('divergence_type', models.CharField(choices=[('macd_bullish', 'MACD Bullish Divergence'), ('macd_bearish', 'MACD Bearish Divergence'), ('rsi_bullish', 'RSI Bullish Divergence'), ('rsi_bearish', 'RSI Bearish Divergence')], max_length=20)),
                ('start_timestamp', models.DateTimeField()),
                ('start_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('start_indicator_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('end_timestamp', models.DateTimeField()),
                ('end_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('end_indicator_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergences', to='datafeeds.symbol')),
            ],
            options={
                'ordering': ('symbol', 'timeframe', 'start_timestamp'),
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'start_timestamp'], name='datafeeds_d_symbol__b58f60_idx'), models.Index(fields=['symbol', 'timeframe', 'divergence_type'], name='datafeeds_d_symbol__5a3c97_idx')],
            },
        ),
    ]
