# Generated by Django 4.2.25 on 2025-10-09 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('base_currency', models.CharField(default='USDT', max_length=10)),
                ('quote_universe', models.JSONField(default=list, help_text='Symbols the bot can trade.')),
                ('starting_capital', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='exchanges.exchangeaccount')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='strategies.strategy')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
