# Generated by Django 4.2.25 on 2025-10-09 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exchange_id', models.CharField(help_text='CCXT exchange identifier.', max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, help_text='Some exchanges require an additional password or passphrase.', max_length=255)),
                ('is_testnet', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
