# Generated by Django 4.2.25 on 2025-10-09 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_positions', models.PositiveIntegerField(default=5)),
                ('max_capital_per_position_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of available capital per position.', max_digits=5)),
                ('daily_loss_limit_pct', models.DecimalField(decimal_places=2, default=3.0, help_text='Kill switch threshold for daily drawdown.', max_digits=5)),
                ('max_total_drawdown_pct', models.DecimalField(decimal_places=2, default=25.0, help_text='Circuit breaker threshold for overall drawdown.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
